### ISSUE TITLE
Missing bulk data?

### ISSUE THREAD

**Issue by mikeroqc** [microsoft/azure-data-manager-for-energy-experience-lab#17]
We’ve had a chance to try the latest MEDS release and are seeing a similar problem with the bulk DDMS data missing as we had seen when we tried the Oak Forest preview release.

We also loaded the TNO data using our site.

https://experiencelab7284.azurewebsites.net/dataload 

by Deploying the “open-test-data” spec in Azure.

We see lots of wells, wellbores, and well logs loaded.  When we make a request to DDMS to get the well log header, that works fine.

GET …../api/os-wellbore-ddms/ddms/v3/welllogs/'logId'

When we ask for the bulk data

GET …../api/os-wellbore-ddms/ddms/v3/welllogs/'logId'/data

We get an error.

{
    'detail': 'bulk for record platform7284-opendes:work-product-component--WellLog:000a9129ac8b4880af1c42a097b458bb not found'
}

As an attempt at fixing this, we tried populating the bulk data ourselves from the las files used to create the well log header.  We tried sending both a parquet data file and a json Pandas file to the POST bulk data API.  The first errors that we got back were like this.

{'detail':'Column(s) DT, NPHI, RHOB, GR, DEPT do(es) not match any CurveID of the WellLog record.'}

The well log headers don’t have any CurveID values, so it looks like that prevents the bulk data API from working.

I forced an updated of the CurveID values (set them equal to the mnemonic) on a couple Well Log records to see if that helps.  Then tried updating the bulk data again.  It now takes about 80 seconds for the request to come back, but I still get a 500 error back.

{'detail':'Unexpected error and save bulk'}

I tried both parquet and the json Pandas formats and get the same errors.

Is the intention that the TNO data load should have loaded the bulk data?  If not, do you know why us trying the populate it ourselves may have failed?

Thanks,
Mike

**Comment by Kyle-MSFT** [comment]
@mikeroqc,

This is a known gap in the current release of OSDU that's used by MEDS. As a workaround you can ingest data directly to the wellbore DMS using the api’s (as bulk ingestion won’t register the data with the DMS) here [Tutorial - Work with well data records by using Wellbore DDMS APIs | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fenergy-data-services%2Ftutorial-wellbore-ddms&data=05%7C01%7Ckymille%40microsoft.com%7C5322ad4a1c3f4c702a5e08dafe23fffc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638101727836201735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bl2BvJrpZLwD303ZjRB0NaNp2vhmyzVS75pATF%2Fx6a0%3D&reserved=0)
