### ISSUE TITLE
Postman Issue: Deployed MEDS Instance, getting access denied at Ingestion Workflow while creating Legal Tag

### ISSUE THREAD

**Issue by ankit-goya** [microsoft/azure-data-manager-for-energy-experience-lab#18]
Deployed the MEDS instance successfully, trying to the Manifest Ingestion, successfully got the user token refreshed, getting the access denied while trying to create a legal tag. 

{
    "code": 401,
    "reason": "Access denied",
    "message": "The user is not authorized to perform this action"
}

**Comment by danieljamescarpenter** [comment]
Can you please provide more information? Is this happening with Postman, REST scripts, UI, Swagger, something else? Can you include the request?

- Confirm the data partition you are using is correct.
- Confirm that you have the proper roles to the MEDS instance. This can be done via the Experience Lab web UI.
- Test creating a legal tag from the Experience Lab web UI.
