### ISSUE TITLE
Deployments not working

### ISSUE THREAD

**Issue by EirikHaughom** [microsoft/azure-data-manager-for-energy-experience-lab#26]
Deployments of ExperienceLab are currently broken, with the following error message while running the deploy container (generated from the CreateLab template). 

```
=================================================================================================================
2023-03-01T21:02Z Creating Data Platform
=================================================================================================================

  Be Patient ~1 hour wait...
ERROR: the following arguments are required: --properties/-p

Examples from AI knowledge base:
az resource create --resource-group myRG --name myWeb --resource-type Microsoft.web/sites --properties "{ \"serverFarmId\":\"/subscriptions/{SubID}/resourcegroups/ {ResourceGroup}/providers/Microsoft.Web/serverfarms/{ServicePlan}\" }"
Create a web app with the minimum required configuration information.

az group create --location westus --resource-group MyResourceGroup
Create a new resource group in the West US region.

az group create --location westeurope --resource-group MyResourceGroup --tags {tags}
Create a new resource group. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/group#az_group_create
Read more about the command in reference docs
main: line 568: --properties: command not found
```

I have tested changing the references from Microsoft.OpenEnergyPlatform to Microsoft.MicrosoftEnergyDataServices within the experiencelab.sh file (on the Storage Account) before running the CreateLab (deploy container instance), but it did not change the error above.

**Comment by EirikHaughom** [comment]
@Miller-Kyle This happened to me yesterday after the API version fix. I pulled a fresh control plane (through both cloning the repo and running the Bicep deployment and the "Deploy to Azure" template deployment. I also chosebkew names to not interfere with preexisting resources

I can try again in a few hours and report back.

**Comment by Miller-Kyle** [comment]
Please send me the contents of your control plane's experiencelab.sh. It is found in the control plane storage account.

**Comment by danielscholl** [comment]
Thank you for finding this issue.  This has now been resolved.
